### ISSUE TITLE
Limit time that cookies persist for when set in preview mode

### ISSUE THREAD

**Issue by kingo55** [mint-metrics/mojito-js-delivery#11]
Currently test cookies in preview mode persist for the standard duration set at the container level through `cookieDuration` (60 days is the default).

When previewing experiments, we don't need the cookie to persist for very long. And for tests being developed within staging mode, which have potential conflicts with other live experiments, it can cause experiments to break and cause confusion for users. 

What if we limited the time for cookies set within preview mode?

**Comment by allmywant** [comment]
@kingo55 
Good point! We can limit the time for cookies set within preview mode. The other alternate could be: do not set cookies for preview mode, preview mode works only with the preview parameters.

**Comment by kingo55** [comment]
Cheers David - disabling preview cookies may work for simple tests, but I
think it will be cumbersome for more complex tests.

The more I think about it, the more I feel it would be best to provide some
sort of UI to let you know you're in a test. Google Tag Manager does a
really good job of this:

**Comment by kingo55** [comment]
(No markdown in email replies - attaching image from above message)

![social-interaction-event](https://user-images.githubusercontent.com/2361388/66465915-7e51dc00-eacd-11e9-9560-3d8780757c92.jpg)

**Comment by dapperdrop** [comment]
I'm not big fan of interfaces for preview mode. We end up disabling stuff like the optly ball and the GTM interface, whilst not as annoying, does take up a lot of screen real estate.

Maybe we can consider a half-way point? Small UI element, that can be quickly dismissed (but reappears on next load).

E.g.
![image](https://user-images.githubusercontent.com/48050512/66521593-349ddb80-eb37-11e9-8276-5729cf976744.png)

**Comment by kingo55** [comment]
Agree - and it'll need to be mobile friendly too.

Multiple tests could be active on the same page, so we might need a way to represent multiple:

![Group 8](https://user-images.githubusercontent.com/2361388/66530090-0679c500-eb52-11e9-91b3-df4963901fff.png)

Rather than building this into the library directly, we could save on container weight and side-load this in.

**Comment by dapperdrop** [comment]
With https://github.com/mint-metrics/mojito-chrome-inspector/issues/1 being well-defined now, should this issue be closed? @kingo55 @allmywant

**Comment by allmywant** [comment]
@dapperdrop 
I think so.

**Comment by kingo55** [comment]
@dapperdrop - yes, good point
