### ISSUE TITLE
YAML private dictionary for use in testing / organisation

### ISSUE THREAD

**Issue by kingo55** [mint-metrics/mojito-js-delivery#18]
I had a rough thought the other day - what if we had some private YAML dictionary that was protected from publishing?

E.g. A place to store to store preview URLs and other organisational information for:

1. Automated testing / screenshotting of all the variants of the test for designated pages
2. Organisation of tests via tags

Thoughts?

**Comment by allmywant** [comment]
@kingo55 
Sounds great, we can have a place to store extra infomation, this is helpful.

**Comment by kingo55** [comment]
Do you think automated testing/screenshotting is possible through Gulp @allmywant ?

**Comment by allmywant** [comment]
@kingo55 
It looks fesible. See 
https://developers.google.com/web/updates/2017/04/headless-chrome
https://medium.com/@dschnr/using-headless-chrome-as-an-automated-screenshot-tool-4b07dffba79a
https://developers.google.com/web/updates/2017/06/headless-karma-mocha-chai

**Comment by kingo55** [comment]
Addressed by #76
