### ISSUE TITLE
Refactor this.inTest() and this.getRecipe() functions so we only read storage once

### ISSUE THREAD

**Issue by kingo55** [mint-metrics/mojito-js-delivery#40]
I wonder if we can refactor this.inTest() and this.getRecipe() so that we read the cookie once and store the information from the cookies on the test object for later re-use? e.g. `this.getStoredDecision() -> sets test.options.storedDecision{inTest:1,recipe:0}`

**Comment by allmywant** [comment]
@kingo55 
Good point!

**Comment by kingo55** [comment]
David, you want to take this issue on once we get a couple of the other PRs merged?

I think it will relate to #31 too.

**Comment by allmywant** [comment]
@kingo55 
Yes, I will take this one.

**Comment by allmywant** [comment]
@kingo55 
Please let me know when this one is ready to start.

**Comment by kingo55** [comment]
@allmywant - ready whenever you like, but bear in mind there may be some changes as yet due to #37 (though probably unlikely to affect the `get`/`set` `test`/`recipe` functions I think).
