### ISSUE TITLE
Event tracking for excluded users

### ISSUE THREAD

**Issue by kingo55** [mint-metrics/mojito-js-delivery#55]
For experimenters making heavy use of the [`Mojito.options.excluded` default exclusion rule](https://mojito.mx/docs/js-delivery-customisation#default-exclusion-rule), I think it could be useful to track which useragents are excluded.

Two ways I have thought of for tracking this:

1. Track exclusion for each experiment as it activates
2. Track exclusion when the container loads

### Tracking at activation

 - This is useful because you will be able to see if excluded useragents would have triggered the experiment.
 - The downside is the activation triggers may need to be written in a way that all browsers can run them (and not fire errors)

### Tracking on load

 - This won't need triggers to support excluded useragents
 - It won't tell us exactly who would have triggered the test but was excluded by the flag
 - It won't need any extra tracking in the library (in the shared code we could have a condition - if excluded track this user as excluded)

Be good to hear if you guys have any thoughts on this too..

**Comment by allmywant** [comment]
@kingo55 
Both way looks good, but tracking on load looks better.

**Comment by dapperdrop** [comment]
@kingo55 
I think for simplicity and ease of use, tracking on load is the way to go.

**Comment by kingo55** [comment]
Cheers guys... I think you're right. It may call for a new Snowplow Schema / event context that we have to setup.

**Comment by kingo55** [comment]
Closing as it seems like a problem independent of the library and very much specific to the client/user's tracking.
