### ISSUE TITLE
Releases

### ISSUE THREAD

**Issue by dapperdrop** [mint-metrics/mojito-js-delivery#57]
We should start tagging releases when we do major bug fixes or introduce enhancements to Mojito.

https://help.github.com/en/github/administering-a-repository/managing-releases-in-a-repository

**Comment by kingo55** [comment]
Agreed.

For starters we need to decide the versions of releases. We used them internally e.g. the original version of Mojito JS Delivery was `0.5.0` before we stopped doing it. And the Mojito R Analytics version is based on a flat release number - last one was `R30`.

Also, I think we should also be merging tagged releases into the [main Mojito repository](https://github.com/mint-metrics/mojito) for completeness, like how the Snowplow guys handle it, and make the modular approach clearer.

**Comment by dapperdrop** [comment]
Should we do releases retrospectively as well? It seems like we can tag specific commits, so it might make sense to go back and tag up the major/minor versions against certain commits.

**Comment by kingo55** [comment]
Might be useful to get the hang of tagging releases to tag the older commits.

**Comment by dapperdrop** [comment]
Releases have been retroactively added. Moving forward, we will be regularly tagging release points.

Closing issue.
