### ISSUE TITLE
Allow test objects without trigger functions for remote triggers / MVT split tests

### ISSUE THREAD

**Issue by kingo55** [mint-metrics/mojito-js-delivery#58]
There are a few cases where we wouldn't need a trigger function for experiments e.g.:

 - MVTs where we might activate two experiments at the same time from the one trigger
 - [Remotely triggered experiments](https://mojito.mx/docs/example-js-delivery-cross-trigger) (i.e. tigger is outside of the experiment) 

However we fire an error when a testObject doesn't have a trigger function. This was originally by design, but it's probably worth revisiting in case we build more experiments like the above.

**Comment by allmywant** [comment]
@kingo55 
I think we can remove that check and add another check beore running ```this.options.trigger(this);```.

**Comment by kingo55** [comment]
addressed by #77
